healthcare/basic/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

app_name = 'basic'

urlpatterns = [
    path('', views.home, name='home'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path('buy-product/<int:product_id>/', views.buy_product_view, name='buy_product'),
    path("get_product_price", views.get_product_price, name="get_product_price"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthcare/healthcare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from basic import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic.urls')),
    path('accounts/login/',views.home),
    path('payment/', include('payment_support.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(),name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),
]

healthcare/payment_support/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static

app_name = 'payment_support'

urlpatterns = [
    path('execute_payment/', views.execute_payment, name='execute_payment'),
    path('payment-failed/', views.payment_failed, name='payment_failed'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('create-payment/<int:product_id>/', views.create_payment, name='create_payment'),
    path('create-allpayment/', views.create_allpayment, name='create_allpayment'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthcare/basic/models.py
from django.db import models

# Create your models here.

healthcare/basic/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)
	
	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

healthcare/basic/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import NewUserForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from payment_support.models import Product, Purchase, Order
from payment_support.helpers import get_object_or_none
from django.http import JsonResponse


def about_us_view(request):
    return render(request, 'basic/about_us.html')


def home(request):
    payment_status = request.session.pop('payment_status', None)
    print("\n==================orders===========================")

    try:
        orders = Order.objects.filter(customer=request.user)
        print("\n==================orders===========================")
        prev_purchase = [order.product.id for order in orders]
        print(prev_purchase)

        prev_purchase = Purchase.objects.get(buyer=request.user)
        prev_purchased_stages = [prev_purchase.stage1, prev_purchase.stage2, prev_purchase.stage3]
        prev_purchases = [i+1 for i, stage in enumerate(prev_purchased_stages) if stage]
        # print(prev_purchases)
    
        bought_all = sum(prev_purchased_stages) == len(prev_purchased_stages)
        # print(bought_all)

    except Exception as e:
        print(e)

        prev_purchases = []
        bought_all = False

    next_allow_product = len(prev_purchases) + 1   

    products = Product.objects.all()

    return render(request, 'basic/index.html', {'products': products, 
                                                "prev_purchases": prev_purchases,
                                                "bought_all": bought_all,
                                                "next_allow_product": next_allow_product,
                                                "payment_status": payment_status})


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            # return render(request, 'homepage/index.html')
            return redirect("basic:home")
        messages.error(request, "Unsuccessful registration. Invalid information.")
        # need to send error msg to the front end 
                
    return redirect("basic:home")


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')                                                               
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Hello! welcome back {username}.")
                return redirect("basic:home")
            else:
                print("Invalid user name or password ")
                messages.error(request,"Invalid username or password.")
        else:
            print("invalid user name or password")
            messages.error(request,"Invalid username or password!!!!.")
        
    return redirect("basic:home")


# --- remove --
def buy_product_view(request, product_id):
    print("==================================== buy product view =========================================")
    prev_purchase = get_object_or_none(Purchase, buyer=request.user)
    
    # if already purchased once, skip buy product form
    if prev_purchase and product_id != 0:
        return redirect("payment_support:create_payment", product_id=product_id)
    
    elif prev_purchase and product_id == 0:
        return redirect("payment_support:create_allpayment")

    # else redirect to the buy product form
    # if single product
    # elif product_id != 0:
    #     selected_product = Product.objects.get(pk=product_id)
    #     return render(request, 'basic/buy_product.html', context={"product": selected_product})
    # # if buy all
    # else:
    #     product_price = sum([product.price for product in Product.objects.all()])
    #     return render(request, 'basic/buy_product.html', context={"product_price": product_price})



def get_product_price(request):
    product_id = int(request.GET.get('product_id'))
    
    if product_id == 0:
        product_price = sum([product.price for product in Product.objects.all()])
        return JsonResponse({'price': product_price})
    
    else:
        product = Product.objects.get(pk=product_id)
        return JsonResponse({'price': product.price})

healthcare/basic/templates/basic/about_us.html
{% extends 'basic/base.html' %}
{% load static %}

{% block content %}

<div class="jumbotron">
    <h1 class="display-4">About Us</h1>
    <p class="lead">Healthcare in the United States is largely provided by private sector healthcare facilities, 
        and paid for by a combination of public programs, private insurance, and out-of-pocket payments. 
        The U.S. is the only developed country without a system of universal healthcare, and a significant proportion of its population lacks health insurance.
        The United States spends more on healthcare than any other country, both in absolute terms and as a percentage of GDP.
         However, this expenditure does not necessarily translate into better overall health outcomes compared to other developed nations.
          Coverage varies widely across the population, with certain groups, such as the elderly and low-income individuals,
          receiving more comprehensive care through government programs such as Medicaid and Medicare. </p>
    <hr class="my-4">
    <p>contact us +9876543210</p>
 
  </div>

{% endblock %}

healthcare/basic/templates/basic/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Healthcare Products</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{%static 'assets/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{%static 'assets/css/template_style.css' %}">

    <style>
    
    .error-message {
            color: rgb(48, 88, 73);
        }

    .alert-danger{
      background-color: #618264; 
      border: #EBEBEB; 
      color:white ;
      box-shadow: 0 0 5px #464645;
    }
    .alert-success{
      background-color: #5e6675; 
      border: #EBEBEB; 
      color:white ;
      box-shadow: 0 0 5px #464645;
    }

    .step {
      /* background-color: #ececea; */
      padding: 10px;
      /* border: 1px solid #d6d8db; */
      border-radius: 8px;
      /* box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); */
      margin-bottom: 10px;
      /* transition: transform 0.3s ease-in-out; */
    }

    /* .step:hover {
      transform: scale(1.01);
    } */

    .step h4 {
      color: #a9ac0a;
    }

    .step p {
      color: #495057;
    }

    </style>
</head>
<body>
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{% url 'basic:home' %}" class="logo">
                            <img src="{%static 'assets/images/logo.png' %}" alt="HealthCare"/>
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a href="#welcome" class="active">Home</a></li>
                            <li><a href="#testimonials about-us">About Us</a></li>
                            <li><a href="#contact-us">Contact Us</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'basic:logout' %}">Logout</a></li>
                            {% endif %}

                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>

   
    {% block content %}
    {% endblock %}

  <!-- Footer -->
  <footer class="bg-dark mt-5 text-center text-lg-start text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Company name
            </h6>
            <p>
              HealthCare center
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
            <p>
              <a class="text-white">Health Diagnosis</a>
            </p>
            
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->

    <div class="text-center p-3"
         style="background-color: rgba(0, 0, 0, 0.2)" >
      © 2020 Copyright
    </div>

  </footer>

   <!-- jQuery -->
   <script src="{%static 'assets/js/jquery-2.1.0.min.js' %}"></script>
  

   <!-- Bootstrap -->
   <script src="{%static 'assets/js/popper.js' %}"></script>
   <script src="{%static 'assets/js/bootstrap.min.js' %}"></script>

   <!-- Plugins -->
   <script src="{%static 'assets/js/scrollreveal.min.js' %}"></script>
   <script src="{%static 'assets/js/waypoints.min.js' %}"></script>
   <script src="{%static 'assets/js/jquery.counterup.min.js' %}"></script>
   <script src="{%static 'assets/js/imgfix.min.js' %}"></script> 
   
   <!-- Global Init -->
   <script src="{%static 'assets/js/custom.js' %}"></script>

    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<!-- for buy_product form -->
<script>
  // Add an event listener to the checkbox
  document.getElementById("termsAndConditions").addEventListener("change", function () {
      // Get the submit button
      var submitButton = document.getElementById("submitButton");

      // Enable or disable the submit button based on the checkbox state
      if (this.checked) {
          submitButton.removeAttribute("disabled");
      } else {
          submitButton.setAttribute("disabled", "disabled");
      }
  });





  $('.buy_product_btn').click(function() {
          var productId = $(this).data('product-id');
          $.ajax({
                  url: '{% url "basic:get_product_price" %}',
                  data: {'product_id': productId},
                  dataType: 'json',
                  success: function(data) {
                      $('#price').text(data.price);
              }
      });
  });


  // handling alert message 
  // Automatically close the success alert after 2 seconds
  document.addEventListener("DOMContentLoaded", function () {
      var successAlert = document.getElementById("success-alert");
      if (successAlert) {
          setTimeout(function () {
              successAlert.classList.remove("show");
          }, 4000); // Adjust the time in milliseconds (e.g., 2000ms = 2 seconds)
      }
  });

  // Automatically close the failure alert after 5 seconds
  document.addEventListener("DOMContentLoaded", function () {
      var failureAlert = document.getElementById("failure-alert");
      if (failureAlert) {
          setTimeout(function () {
              failureAlert.classList.remove("show");
          }, 4000); // Adjust the time in milliseconds (e.g., 2000ms = 2 seconds)
      }
  });



</script>




  </body>
</html>

healthcare/basic/templates/basic/buy_product.html
<div class="modal fade" id="buyProductModal" tabindex="-1" role="dialog" aria-labelledby="buyProductModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="buyProductModal">Buy product</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        
            <form method="POST" class="mt-4" id="payment_KYC">

            {% csrf_token %}
                <div class="form-group">
                <label for="firstName">Buyer's Name:</label>
                <input type="text" class="form-control" id="firstName" name="buyer_name" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email Address:</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="form-group text-center mt-4">
                        <label for="product_price">Price: <span id="price"></span> </label>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="termsAndConditions" name="termsAndConditions" required>
                        <label class="form-check-label" for="termsAndConditions">I agree to the terms and conditions</label>
                    </div>
                    <button type="submit" id="submitButton" class="btn btn-primary mt-3" disabled>Buy Now</button>
            </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    
    document.addEventListener('DOMContentLoaded', function() {
        // Get all elements with the class 'buy_product_btn'
        var productButtons = document.querySelectorAll('.buy_product_btn');

        // Get the form element
        var paymentForm = document.getElementById('payment_KYC');

        // Add a click event listener to each product button
        productButtons.forEach(function(button) {
            button.addEventListener('click', function() {
                // Get the product ID from the button's data attribute
                var productId = this.getAttribute('data-product-id');
                var newActionURL = ""
                // Construct the new action URL based on the product ID
                console.log(productId)
                if (productId == "0"){
                    newActionURL = "{% url 'payment_support:create_allpayment' %}";

                }
                else{
                    newActionURL = "/payment/create-payment/"+productId+"/";
                }
                // Update the form's action attribute
                paymentForm.setAttribute('action', newActionURL);

                // Optional: Submit the form automatically if needed
                // paymentForm.submit();
            });
        });
    });


        
        $('.price').each(function() {
            var productId = $(this).data('product-id');
            $.ajax({
                url: '{% url "basic:get_product_price" %}',
                data: {'product_id': productId},
                dataType: 'json',
                success: function(data) {
                    $('#price' + productId).text(data.price);
                }
            });
        });



    // Add an event listener to the checkbox
    document.getElementById("termsAndConditions").addEventListener("change", function () {
        // Get the submit button
        var submitButton = document.getElementById("submitButton");
  
        // Enable or disable the submit button based on the checkbox state
        if (this.checked) {
            submitButton.removeAttribute("disabled");
        } else {
            submitButton.setAttribute("disabled", "disabled");
        }
    });
  </script>

healthcare/basic/templates/basic/login.html
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="loginModalLabel">Login</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Login Form -->
          <form method="POST" action="{% url 'basic:login' %}" class="mt-4 pb-5">
            {% csrf_token %}
            <div class="form-group">
              <label for="username">Username</label>
              <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username" required>
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" required>
            </div>
           
            <div class="text-center"> <!-- Center the button within the form -->
                <button type="submit" class="btn" style="background-color: #FBD85D; color: #000; border: none; padding: 10px 20%; width: auto;">Login</button>
            </div>
          
          </form>
          <div class="text-center mt-3">
            Don't have an account? <a data-target="#registerModal" data-toggle="modal" data-dismiss="modal" style="cursor: pointer; color:#5279ec">Register</a>
          </div>
          <div class="text-center mt-3">
            Forgot your password? <a href="{% url 'reset_password' %}"  style="cursor: pointer; color:#5279ec">Reset</a>
          </div>
            <!-- <form method="POST" class="mt-4 pb-5">
                <div class="text-center">
                <button class="btn btn-primary btn-block" type="submit">Login</button>
                </div>
          </form> -->
        </div>
      </div>
    </div>
  </div>

healthcare/basic/templates/basic/register.html
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="registerModalLabel">Register</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{% url 'basic:register' %}" onsubmit="return validateForm()">
            {% csrf_token %}
                <div class="form-group">
                  <label for="username">User Name</label>
                  <input type="text" class="form-control" id="username" name="username" placeholder="Enter your full name" required>
                  <div id="usernameError" class="error-message"></div>
                </div>
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" required>
                  <div id="emailError" class="error-message"></div>
                </div>
                
                <div class="form-group">
                  <label for="password1">Password</label>
                  <div class="input-group">
                  <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter a password" required>
                  <div class="input-group-append" style="margin-left: 3px;">
                    <button class="btn btn-light" type="button" id="togglePassword1">
                      <i class="fas fa-eye"></i>
                  </button>
                  </div>
                </div>
                <div id="passwordError" class="error-message"></div>
                </div>

                <div class="form-group">
                  <label for="password2">conform password</label>
                  <div class="input-group">
                  <input type="password" class="form-control" id="password2" name="password2" placeholder="Conform password" required>
                    <div class="input-group-append" style="margin-left: 3px;">
                      <button class="btn btn-light" type="button" id="togglePassword2">
                        <i class="fas fa-eye"></i>
                    </button>
                  </div>
                </div>
                <div id="confirmPasswordError" class="error-message"></div>
                </div>
                <div class="text-center"> <!-- Center the button within the form -->
                    <button type="submit" class="btn" style="background-color: #FBD85D; color: #000; border: none; padding: 10px 20%; width: auto;">Register</button>
                </div>
              </form>
          <div class="text-center mt-3">
            Already have an account? <a data-target="#loginModal"  data-toggle="modal" data-dismiss="modal" style="cursor: pointer; color: #5279ec; ">Login</a>
          </div>
            <!-- <form method="POST" class="mt-4 pb-5">
                <div class="text-center">
                <button class="btn btn-primary btn-block" type="submit">Login</button>
                </div>
          </form> -->
        </div>
      </div>
    </div>
  </div>

  <script>

document.addEventListener('DOMContentLoaded', function () {
            // Toggle password visibility
            var togglePasswordButton = document.getElementById('togglePassword1');
            togglePasswordButton.addEventListener('click', function () {
                var passwordField = document.getElementById('password1');
                var passwordFieldType = passwordField.getAttribute('type');
                
                if (passwordFieldType === 'password') {
                    passwordField.setAttribute('type', 'text');
                    this.querySelector('i').classList.remove('fa-eye');
                    this.querySelector('i').classList.add('fa-eye-slash');
                } else {
                    passwordField.setAttribute('type', 'password');
                    this.querySelector('i').classList.remove('fa-eye-slash');
                    this.querySelector('i').classList.add('fa-eye');
                }
            });


            // toggle confirm password visibility
            // Toggle password visibility
            var togglePasswordButton = document.getElementById('togglePassword2');
            togglePasswordButton.addEventListener('click', function () {
                var passwordField = document.getElementById('password2');
                var passwordFieldType = passwordField.getAttribute('type');
                
                if (passwordFieldType === 'password') {
                    passwordField.setAttribute('type', 'text');
                    this.querySelector('i').classList.remove('fa-eye');
                    this.querySelector('i').classList.add('fa-eye-slash');
                } else {
                    passwordField.setAttribute('type', 'password');
                    this.querySelector('i').classList.remove('fa-eye-slash');
                    this.querySelector('i').classList.add('fa-eye');
                }
            });
        });

  // registration form validation
  function validateForm() {
            console.log("validating form");
            var username = document.getElementById("username").value;
            var email = document.getElementById("email").value;
            var password = document.getElementById("password1").value;
            var confirmPassword = document.getElementById("password2").value;

            // Clear any previous error messages
            clearErrorMessages();

            var isValid = true;

            // // Username validation
            // if (!/^\w{3,20}$/.test(username)) {
            //     displayError("usernameError", "⚠️ Username must be 3-20 characters, only letters, numbers, and underscores allowed.");
            //     isValid = false;
            // }

            // Email validation
            if (!/^\S+@\S+\.\S+$/.test(email)) {
                displayError("emailError", "⚠️ Please enter a valid email address.");
                isValid = false;
            }

            // Password validation
            if (password.length < 8) {
                displayError("passwordError", "⚠️ Password must be at least 8 characters long.");
                isValid = false;
            }

            if (!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&]).{8,}$/.test(password)) {
                displayError("passwordError", "⚠️ Password should contain at least one lowercase letter, one uppercase letter, one number, and one special character.");
                isValid = false;
            }

            // Confirm Password validation
            if (password !== confirmPassword) {
                displayError("confirmPasswordError", "⚠️ Password and Confirm Password do not match.");
                isValid = false;
            }

            if (isValid) {
                modal.style.display = "none"; // Close the modal on success
            }

            return isValid;
        }

  function displayError(id, message) {
            var errorElement = document.getElementById(id);
            errorElement.innerText = message;
        }

  function clearErrorMessages() {
            var errorMessages = document.getElementsByClassName("error-message");
            for (var i = 0; i < errorMessages.length; i++) {
                errorMessages[i].innerText = "";
            }
        }
  </script>